/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSoundsRouteImport } from './routes/_app/sounds'
import { Route as AppGeneralInfoRouteImport } from './routes/_app/general-info'
import { Route as AppEmbeddedTexturesRouteImport } from './routes/_app/embedded-textures'
import { Route as AppCodeRouteImport } from './routes/_app/code'
import { Route as AppSpritesIndexRouteImport } from './routes/_app/sprites.index'
import { Route as AppSoundsNameRouteImport } from './routes/_app/sounds.$name'
import { Route as AppEmbeddedTexturesIdRouteImport } from './routes/_app/embedded-textures.$id'
import { Route as AppCodeNameRouteImport } from './routes/_app/code.$name'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSoundsRoute = AppSoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGeneralInfoRoute = AppGeneralInfoRouteImport.update({
  id: '/general-info',
  path: '/general-info',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmbeddedTexturesRoute = AppEmbeddedTexturesRouteImport.update({
  id: '/embedded-textures',
  path: '/embedded-textures',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSpritesIndexRoute = AppSpritesIndexRouteImport.update({
  id: '/sprites/',
  path: '/sprites/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSoundsNameRoute = AppSoundsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppSoundsRoute,
} as any)
const AppEmbeddedTexturesIdRoute = AppEmbeddedTexturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmbeddedTexturesRoute,
} as any)
const AppCodeNameRoute = AppCodeNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppCodeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof AppCodeRouteWithChildren
  '/embedded-textures': typeof AppEmbeddedTexturesRouteWithChildren
  '/general-info': typeof AppGeneralInfoRoute
  '/sounds': typeof AppSoundsRouteWithChildren
  '/code/$name': typeof AppCodeNameRoute
  '/embedded-textures/$id': typeof AppEmbeddedTexturesIdRoute
  '/sounds/$name': typeof AppSoundsNameRoute
  '/sprites/': typeof AppSpritesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof AppCodeRouteWithChildren
  '/embedded-textures': typeof AppEmbeddedTexturesRouteWithChildren
  '/general-info': typeof AppGeneralInfoRoute
  '/sounds': typeof AppSoundsRouteWithChildren
  '/code/$name': typeof AppCodeNameRoute
  '/embedded-textures/$id': typeof AppEmbeddedTexturesIdRoute
  '/sounds/$name': typeof AppSoundsNameRoute
  '/sprites': typeof AppSpritesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/code': typeof AppCodeRouteWithChildren
  '/_app/embedded-textures': typeof AppEmbeddedTexturesRouteWithChildren
  '/_app/general-info': typeof AppGeneralInfoRoute
  '/_app/sounds': typeof AppSoundsRouteWithChildren
  '/_app/code/$name': typeof AppCodeNameRoute
  '/_app/embedded-textures/$id': typeof AppEmbeddedTexturesIdRoute
  '/_app/sounds/$name': typeof AppSoundsNameRoute
  '/_app/sprites/': typeof AppSpritesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/embedded-textures'
    | '/general-info'
    | '/sounds'
    | '/code/$name'
    | '/embedded-textures/$id'
    | '/sounds/$name'
    | '/sprites/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/embedded-textures'
    | '/general-info'
    | '/sounds'
    | '/code/$name'
    | '/embedded-textures/$id'
    | '/sounds/$name'
    | '/sprites'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/code'
    | '/_app/embedded-textures'
    | '/_app/general-info'
    | '/_app/sounds'
    | '/_app/code/$name'
    | '/_app/embedded-textures/$id'
    | '/_app/sounds/$name'
    | '/_app/sprites/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/sounds': {
      id: '/_app/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof AppSoundsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/general-info': {
      id: '/_app/general-info'
      path: '/general-info'
      fullPath: '/general-info'
      preLoaderRoute: typeof AppGeneralInfoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/embedded-textures': {
      id: '/_app/embedded-textures'
      path: '/embedded-textures'
      fullPath: '/embedded-textures'
      preLoaderRoute: typeof AppEmbeddedTexturesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/code': {
      id: '/_app/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sprites/': {
      id: '/_app/sprites/'
      path: '/sprites'
      fullPath: '/sprites/'
      preLoaderRoute: typeof AppSpritesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sounds/$name': {
      id: '/_app/sounds/$name'
      path: '/$name'
      fullPath: '/sounds/$name'
      preLoaderRoute: typeof AppSoundsNameRouteImport
      parentRoute: typeof AppSoundsRoute
    }
    '/_app/embedded-textures/$id': {
      id: '/_app/embedded-textures/$id'
      path: '/$id'
      fullPath: '/embedded-textures/$id'
      preLoaderRoute: typeof AppEmbeddedTexturesIdRouteImport
      parentRoute: typeof AppEmbeddedTexturesRoute
    }
    '/_app/code/$name': {
      id: '/_app/code/$name'
      path: '/$name'
      fullPath: '/code/$name'
      preLoaderRoute: typeof AppCodeNameRouteImport
      parentRoute: typeof AppCodeRoute
    }
  }
}

interface AppCodeRouteChildren {
  AppCodeNameRoute: typeof AppCodeNameRoute
}

const AppCodeRouteChildren: AppCodeRouteChildren = {
  AppCodeNameRoute: AppCodeNameRoute,
}

const AppCodeRouteWithChildren =
  AppCodeRoute._addFileChildren(AppCodeRouteChildren)

interface AppEmbeddedTexturesRouteChildren {
  AppEmbeddedTexturesIdRoute: typeof AppEmbeddedTexturesIdRoute
}

const AppEmbeddedTexturesRouteChildren: AppEmbeddedTexturesRouteChildren = {
  AppEmbeddedTexturesIdRoute: AppEmbeddedTexturesIdRoute,
}

const AppEmbeddedTexturesRouteWithChildren =
  AppEmbeddedTexturesRoute._addFileChildren(AppEmbeddedTexturesRouteChildren)

interface AppSoundsRouteChildren {
  AppSoundsNameRoute: typeof AppSoundsNameRoute
}

const AppSoundsRouteChildren: AppSoundsRouteChildren = {
  AppSoundsNameRoute: AppSoundsNameRoute,
}

const AppSoundsRouteWithChildren = AppSoundsRoute._addFileChildren(
  AppSoundsRouteChildren,
)

interface AppRouteRouteChildren {
  AppCodeRoute: typeof AppCodeRouteWithChildren
  AppEmbeddedTexturesRoute: typeof AppEmbeddedTexturesRouteWithChildren
  AppGeneralInfoRoute: typeof AppGeneralInfoRoute
  AppSoundsRoute: typeof AppSoundsRouteWithChildren
  AppSpritesIndexRoute: typeof AppSpritesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCodeRoute: AppCodeRouteWithChildren,
  AppEmbeddedTexturesRoute: AppEmbeddedTexturesRouteWithChildren,
  AppGeneralInfoRoute: AppGeneralInfoRoute,
  AppSoundsRoute: AppSoundsRouteWithChildren,
  AppSpritesIndexRoute: AppSpritesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
