/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppGeneralInfoRouteImport } from './routes/_app/general-info'
import { Route as AppCodeIndexRouteImport } from './routes/_app/code.index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppGeneralInfoRoute = AppGeneralInfoRouteImport.update({
  id: '/general-info',
  path: '/general-info',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCodeIndexRoute = AppCodeIndexRouteImport.update({
  id: '/code/',
  path: '/code/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/general-info': typeof AppGeneralInfoRoute
  '/code/': typeof AppCodeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/general-info': typeof AppGeneralInfoRoute
  '/code': typeof AppCodeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/general-info': typeof AppGeneralInfoRoute
  '/_app/code/': typeof AppCodeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/general-info' | '/code/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/general-info' | '/code'
  id: '__root__' | '/' | '/_app' | '/_app/general-info' | '/_app/code/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/general-info': {
      id: '/_app/general-info'
      path: '/general-info'
      fullPath: '/general-info'
      preLoaderRoute: typeof AppGeneralInfoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/code/': {
      id: '/_app/code/'
      path: '/code'
      fullPath: '/code/'
      preLoaderRoute: typeof AppCodeIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppGeneralInfoRoute: typeof AppGeneralInfoRoute
  AppCodeIndexRoute: typeof AppCodeIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppGeneralInfoRoute: AppGeneralInfoRoute,
  AppCodeIndexRoute: AppCodeIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
