/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppCodeRouteImport } from './routes/_app/code'
import { Route as AppEmbeddedTexturesRouteImport } from './routes/_app/embedded-textures'
import { Route as AppGeneralInfoRouteImport } from './routes/_app/general-info'
import { Route as AppSoundsRouteImport } from './routes/_app/sounds'
import { Route as AppAudioGroupsIndexRouteImport } from './routes/_app/audio-groups.index'
import { Route as AppCodeLocalsIndexRouteImport } from './routes/_app/code-locals.index'
import { Route as AppCodeNameRouteImport } from './routes/_app/code.$name'
import { Route as AppEmbeddedTexturesIdRouteImport } from './routes/_app/embedded-textures.$id'
import { Route as AppExtensionsIndexRouteImport } from './routes/_app/extensions.index'
import { Route as AppFontsIndexRouteImport } from './routes/_app/fonts.index'
import { Route as AppFunctionsIndexRouteImport } from './routes/_app/functions.index'
import { Route as AppObjectsIndexRouteImport } from './routes/_app/objects.index'
import { Route as AppPathsIndexRouteImport } from './routes/_app/paths.index'
import { Route as AppRoomsIndexRouteImport } from './routes/_app/rooms.index'
import { Route as AppScriptsIndexRouteImport } from './routes/_app/scripts.index'
import { Route as AppShadersIndexRouteImport } from './routes/_app/shaders.index'
import { Route as AppSoundsNameRouteImport } from './routes/_app/sounds.$name'
import { Route as AppSpritesIndexRouteImport } from './routes/_app/sprites.index'
import { Route as AppStringsIndexRouteImport } from './routes/_app/strings.index'
import { Route as AppTextureGroupsIndexRouteImport } from './routes/_app/texture-groups.index'
import { Route as AppTexturePagesIndexRouteImport } from './routes/_app/texture-pages.index'
import { Route as AppTileSetsIndexRouteImport } from './routes/_app/tile-sets.index'
import { Route as AppTimelinesIndexRouteImport } from './routes/_app/timelines.index'
import { Route as AppVariablesIndexRouteImport } from './routes/_app/variables.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCodeRoute = AppCodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEmbeddedTexturesRoute = AppEmbeddedTexturesRouteImport.update({
  id: '/embedded-textures',
  path: '/embedded-textures',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppGeneralInfoRoute = AppGeneralInfoRouteImport.update({
  id: '/general-info',
  path: '/general-info',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSoundsRoute = AppSoundsRouteImport.update({
  id: '/sounds',
  path: '/sounds',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAudioGroupsIndexRoute = AppAudioGroupsIndexRouteImport.update({
  id: '/audio-groups/',
  path: '/audio-groups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCodeLocalsIndexRoute = AppCodeLocalsIndexRouteImport.update({
  id: '/code-locals/',
  path: '/code-locals/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCodeNameRoute = AppCodeNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppCodeRoute,
} as any)
const AppEmbeddedTexturesIdRoute = AppEmbeddedTexturesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppEmbeddedTexturesRoute,
} as any)
const AppExtensionsIndexRoute = AppExtensionsIndexRouteImport.update({
  id: '/extensions/',
  path: '/extensions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFontsIndexRoute = AppFontsIndexRouteImport.update({
  id: '/fonts/',
  path: '/fonts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFunctionsIndexRoute = AppFunctionsIndexRouteImport.update({
  id: '/functions/',
  path: '/functions/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppObjectsIndexRoute = AppObjectsIndexRouteImport.update({
  id: '/objects/',
  path: '/objects/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPathsIndexRoute = AppPathsIndexRouteImport.update({
  id: '/paths/',
  path: '/paths/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppRoomsIndexRoute = AppRoomsIndexRouteImport.update({
  id: '/rooms/',
  path: '/rooms/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppScriptsIndexRoute = AppScriptsIndexRouteImport.update({
  id: '/scripts/',
  path: '/scripts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppShadersIndexRoute = AppShadersIndexRouteImport.update({
  id: '/shaders/',
  path: '/shaders/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSoundsNameRoute = AppSoundsNameRouteImport.update({
  id: '/$name',
  path: '/$name',
  getParentRoute: () => AppSoundsRoute,
} as any)
const AppSpritesIndexRoute = AppSpritesIndexRouteImport.update({
  id: '/sprites/',
  path: '/sprites/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStringsIndexRoute = AppStringsIndexRouteImport.update({
  id: '/strings/',
  path: '/strings/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTextureGroupsIndexRoute = AppTextureGroupsIndexRouteImport.update({
  id: '/texture-groups/',
  path: '/texture-groups/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTexturePagesIndexRoute = AppTexturePagesIndexRouteImport.update({
  id: '/texture-pages/',
  path: '/texture-pages/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTileSetsIndexRoute = AppTileSetsIndexRouteImport.update({
  id: '/tile-sets/',
  path: '/tile-sets/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimelinesIndexRoute = AppTimelinesIndexRouteImport.update({
  id: '/timelines/',
  path: '/timelines/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppVariablesIndexRoute = AppVariablesIndexRouteImport.update({
  id: '/variables/',
  path: '/variables/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/code': typeof AppCodeRouteWithChildren
  '/embedded-textures': typeof AppEmbeddedTexturesRouteWithChildren
  '/general-info': typeof AppGeneralInfoRoute
  '/sounds': typeof AppSoundsRouteWithChildren
  '/code/$name': typeof AppCodeNameRoute
  '/embedded-textures/$id': typeof AppEmbeddedTexturesIdRoute
  '/sounds/$name': typeof AppSoundsNameRoute
  '/audio-groups/': typeof AppAudioGroupsIndexRoute
  '/code-locals/': typeof AppCodeLocalsIndexRoute
  '/extensions/': typeof AppExtensionsIndexRoute
  '/fonts/': typeof AppFontsIndexRoute
  '/functions/': typeof AppFunctionsIndexRoute
  '/objects/': typeof AppObjectsIndexRoute
  '/paths/': typeof AppPathsIndexRoute
  '/rooms/': typeof AppRoomsIndexRoute
  '/scripts/': typeof AppScriptsIndexRoute
  '/shaders/': typeof AppShadersIndexRoute
  '/sprites/': typeof AppSpritesIndexRoute
  '/strings/': typeof AppStringsIndexRoute
  '/texture-groups/': typeof AppTextureGroupsIndexRoute
  '/texture-pages/': typeof AppTexturePagesIndexRoute
  '/tile-sets/': typeof AppTileSetsIndexRoute
  '/timelines/': typeof AppTimelinesIndexRoute
  '/variables/': typeof AppVariablesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/code': typeof AppCodeRouteWithChildren
  '/embedded-textures': typeof AppEmbeddedTexturesRouteWithChildren
  '/general-info': typeof AppGeneralInfoRoute
  '/sounds': typeof AppSoundsRouteWithChildren
  '/code/$name': typeof AppCodeNameRoute
  '/embedded-textures/$id': typeof AppEmbeddedTexturesIdRoute
  '/sounds/$name': typeof AppSoundsNameRoute
  '/audio-groups': typeof AppAudioGroupsIndexRoute
  '/code-locals': typeof AppCodeLocalsIndexRoute
  '/extensions': typeof AppExtensionsIndexRoute
  '/fonts': typeof AppFontsIndexRoute
  '/functions': typeof AppFunctionsIndexRoute
  '/objects': typeof AppObjectsIndexRoute
  '/paths': typeof AppPathsIndexRoute
  '/rooms': typeof AppRoomsIndexRoute
  '/scripts': typeof AppScriptsIndexRoute
  '/shaders': typeof AppShadersIndexRoute
  '/sprites': typeof AppSpritesIndexRoute
  '/strings': typeof AppStringsIndexRoute
  '/texture-groups': typeof AppTextureGroupsIndexRoute
  '/texture-pages': typeof AppTexturePagesIndexRoute
  '/tile-sets': typeof AppTileSetsIndexRoute
  '/timelines': typeof AppTimelinesIndexRoute
  '/variables': typeof AppVariablesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/code': typeof AppCodeRouteWithChildren
  '/_app/embedded-textures': typeof AppEmbeddedTexturesRouteWithChildren
  '/_app/general-info': typeof AppGeneralInfoRoute
  '/_app/sounds': typeof AppSoundsRouteWithChildren
  '/_app/code/$name': typeof AppCodeNameRoute
  '/_app/embedded-textures/$id': typeof AppEmbeddedTexturesIdRoute
  '/_app/sounds/$name': typeof AppSoundsNameRoute
  '/_app/audio-groups/': typeof AppAudioGroupsIndexRoute
  '/_app/code-locals/': typeof AppCodeLocalsIndexRoute
  '/_app/extensions/': typeof AppExtensionsIndexRoute
  '/_app/fonts/': typeof AppFontsIndexRoute
  '/_app/functions/': typeof AppFunctionsIndexRoute
  '/_app/objects/': typeof AppObjectsIndexRoute
  '/_app/paths/': typeof AppPathsIndexRoute
  '/_app/rooms/': typeof AppRoomsIndexRoute
  '/_app/scripts/': typeof AppScriptsIndexRoute
  '/_app/shaders/': typeof AppShadersIndexRoute
  '/_app/sprites/': typeof AppSpritesIndexRoute
  '/_app/strings/': typeof AppStringsIndexRoute
  '/_app/texture-groups/': typeof AppTextureGroupsIndexRoute
  '/_app/texture-pages/': typeof AppTexturePagesIndexRoute
  '/_app/tile-sets/': typeof AppTileSetsIndexRoute
  '/_app/timelines/': typeof AppTimelinesIndexRoute
  '/_app/variables/': typeof AppVariablesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/code'
    | '/embedded-textures'
    | '/general-info'
    | '/sounds'
    | '/code/$name'
    | '/embedded-textures/$id'
    | '/sounds/$name'
    | '/audio-groups/'
    | '/code-locals/'
    | '/extensions/'
    | '/fonts/'
    | '/functions/'
    | '/objects/'
    | '/paths/'
    | '/rooms/'
    | '/scripts/'
    | '/shaders/'
    | '/sprites/'
    | '/strings/'
    | '/texture-groups/'
    | '/texture-pages/'
    | '/tile-sets/'
    | '/timelines/'
    | '/variables/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/code'
    | '/embedded-textures'
    | '/general-info'
    | '/sounds'
    | '/code/$name'
    | '/embedded-textures/$id'
    | '/sounds/$name'
    | '/audio-groups'
    | '/code-locals'
    | '/extensions'
    | '/fonts'
    | '/functions'
    | '/objects'
    | '/paths'
    | '/rooms'
    | '/scripts'
    | '/shaders'
    | '/sprites'
    | '/strings'
    | '/texture-groups'
    | '/texture-pages'
    | '/tile-sets'
    | '/timelines'
    | '/variables'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/code'
    | '/_app/embedded-textures'
    | '/_app/general-info'
    | '/_app/sounds'
    | '/_app/code/$name'
    | '/_app/embedded-textures/$id'
    | '/_app/sounds/$name'
    | '/_app/audio-groups/'
    | '/_app/code-locals/'
    | '/_app/extensions/'
    | '/_app/fonts/'
    | '/_app/functions/'
    | '/_app/objects/'
    | '/_app/paths/'
    | '/_app/rooms/'
    | '/_app/scripts/'
    | '/_app/shaders/'
    | '/_app/sprites/'
    | '/_app/strings/'
    | '/_app/texture-groups/'
    | '/_app/texture-pages/'
    | '/_app/tile-sets/'
    | '/_app/timelines/'
    | '/_app/variables/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/code': {
      id: '/_app/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof AppCodeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/embedded-textures': {
      id: '/_app/embedded-textures'
      path: '/embedded-textures'
      fullPath: '/embedded-textures'
      preLoaderRoute: typeof AppEmbeddedTexturesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/general-info': {
      id: '/_app/general-info'
      path: '/general-info'
      fullPath: '/general-info'
      preLoaderRoute: typeof AppGeneralInfoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sounds': {
      id: '/_app/sounds'
      path: '/sounds'
      fullPath: '/sounds'
      preLoaderRoute: typeof AppSoundsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/audio-groups/': {
      id: '/_app/audio-groups/'
      path: '/audio-groups'
      fullPath: '/audio-groups/'
      preLoaderRoute: typeof AppAudioGroupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/code-locals/': {
      id: '/_app/code-locals/'
      path: '/code-locals'
      fullPath: '/code-locals/'
      preLoaderRoute: typeof AppCodeLocalsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/code/$name': {
      id: '/_app/code/$name'
      path: '/$name'
      fullPath: '/code/$name'
      preLoaderRoute: typeof AppCodeNameRouteImport
      parentRoute: typeof AppCodeRoute
    }
    '/_app/embedded-textures/$id': {
      id: '/_app/embedded-textures/$id'
      path: '/$id'
      fullPath: '/embedded-textures/$id'
      preLoaderRoute: typeof AppEmbeddedTexturesIdRouteImport
      parentRoute: typeof AppEmbeddedTexturesRoute
    }
    '/_app/extensions/': {
      id: '/_app/extensions/'
      path: '/extensions'
      fullPath: '/extensions/'
      preLoaderRoute: typeof AppExtensionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/fonts/': {
      id: '/_app/fonts/'
      path: '/fonts'
      fullPath: '/fonts/'
      preLoaderRoute: typeof AppFontsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/functions/': {
      id: '/_app/functions/'
      path: '/functions'
      fullPath: '/functions/'
      preLoaderRoute: typeof AppFunctionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/objects/': {
      id: '/_app/objects/'
      path: '/objects'
      fullPath: '/objects/'
      preLoaderRoute: typeof AppObjectsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/paths/': {
      id: '/_app/paths/'
      path: '/paths'
      fullPath: '/paths/'
      preLoaderRoute: typeof AppPathsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/rooms/': {
      id: '/_app/rooms/'
      path: '/rooms'
      fullPath: '/rooms/'
      preLoaderRoute: typeof AppRoomsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/scripts/': {
      id: '/_app/scripts/'
      path: '/scripts'
      fullPath: '/scripts/'
      preLoaderRoute: typeof AppScriptsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/shaders/': {
      id: '/_app/shaders/'
      path: '/shaders'
      fullPath: '/shaders/'
      preLoaderRoute: typeof AppShadersIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sounds/$name': {
      id: '/_app/sounds/$name'
      path: '/$name'
      fullPath: '/sounds/$name'
      preLoaderRoute: typeof AppSoundsNameRouteImport
      parentRoute: typeof AppSoundsRoute
    }
    '/_app/sprites/': {
      id: '/_app/sprites/'
      path: '/sprites'
      fullPath: '/sprites/'
      preLoaderRoute: typeof AppSpritesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/strings/': {
      id: '/_app/strings/'
      path: '/strings'
      fullPath: '/strings/'
      preLoaderRoute: typeof AppStringsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/texture-groups/': {
      id: '/_app/texture-groups/'
      path: '/texture-groups'
      fullPath: '/texture-groups/'
      preLoaderRoute: typeof AppTextureGroupsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/texture-pages/': {
      id: '/_app/texture-pages/'
      path: '/texture-pages'
      fullPath: '/texture-pages/'
      preLoaderRoute: typeof AppTexturePagesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/tile-sets/': {
      id: '/_app/tile-sets/'
      path: '/tile-sets'
      fullPath: '/tile-sets/'
      preLoaderRoute: typeof AppTileSetsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/timelines/': {
      id: '/_app/timelines/'
      path: '/timelines'
      fullPath: '/timelines/'
      preLoaderRoute: typeof AppTimelinesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/variables/': {
      id: '/_app/variables/'
      path: '/variables'
      fullPath: '/variables/'
      preLoaderRoute: typeof AppVariablesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppCodeRouteChildren {
  AppCodeNameRoute: typeof AppCodeNameRoute
}

const AppCodeRouteChildren: AppCodeRouteChildren = {
  AppCodeNameRoute: AppCodeNameRoute,
}

const AppCodeRouteWithChildren =
  AppCodeRoute._addFileChildren(AppCodeRouteChildren)

interface AppEmbeddedTexturesRouteChildren {
  AppEmbeddedTexturesIdRoute: typeof AppEmbeddedTexturesIdRoute
}

const AppEmbeddedTexturesRouteChildren: AppEmbeddedTexturesRouteChildren = {
  AppEmbeddedTexturesIdRoute: AppEmbeddedTexturesIdRoute,
}

const AppEmbeddedTexturesRouteWithChildren =
  AppEmbeddedTexturesRoute._addFileChildren(AppEmbeddedTexturesRouteChildren)

interface AppSoundsRouteChildren {
  AppSoundsNameRoute: typeof AppSoundsNameRoute
}

const AppSoundsRouteChildren: AppSoundsRouteChildren = {
  AppSoundsNameRoute: AppSoundsNameRoute,
}

const AppSoundsRouteWithChildren = AppSoundsRoute._addFileChildren(
  AppSoundsRouteChildren,
)

interface AppRouteRouteChildren {
  AppCodeRoute: typeof AppCodeRouteWithChildren
  AppEmbeddedTexturesRoute: typeof AppEmbeddedTexturesRouteWithChildren
  AppGeneralInfoRoute: typeof AppGeneralInfoRoute
  AppSoundsRoute: typeof AppSoundsRouteWithChildren
  AppAudioGroupsIndexRoute: typeof AppAudioGroupsIndexRoute
  AppCodeLocalsIndexRoute: typeof AppCodeLocalsIndexRoute
  AppExtensionsIndexRoute: typeof AppExtensionsIndexRoute
  AppFontsIndexRoute: typeof AppFontsIndexRoute
  AppFunctionsIndexRoute: typeof AppFunctionsIndexRoute
  AppObjectsIndexRoute: typeof AppObjectsIndexRoute
  AppPathsIndexRoute: typeof AppPathsIndexRoute
  AppRoomsIndexRoute: typeof AppRoomsIndexRoute
  AppScriptsIndexRoute: typeof AppScriptsIndexRoute
  AppShadersIndexRoute: typeof AppShadersIndexRoute
  AppSpritesIndexRoute: typeof AppSpritesIndexRoute
  AppStringsIndexRoute: typeof AppStringsIndexRoute
  AppTextureGroupsIndexRoute: typeof AppTextureGroupsIndexRoute
  AppTexturePagesIndexRoute: typeof AppTexturePagesIndexRoute
  AppTileSetsIndexRoute: typeof AppTileSetsIndexRoute
  AppTimelinesIndexRoute: typeof AppTimelinesIndexRoute
  AppVariablesIndexRoute: typeof AppVariablesIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppCodeRoute: AppCodeRouteWithChildren,
  AppEmbeddedTexturesRoute: AppEmbeddedTexturesRouteWithChildren,
  AppGeneralInfoRoute: AppGeneralInfoRoute,
  AppSoundsRoute: AppSoundsRouteWithChildren,
  AppAudioGroupsIndexRoute: AppAudioGroupsIndexRoute,
  AppCodeLocalsIndexRoute: AppCodeLocalsIndexRoute,
  AppExtensionsIndexRoute: AppExtensionsIndexRoute,
  AppFontsIndexRoute: AppFontsIndexRoute,
  AppFunctionsIndexRoute: AppFunctionsIndexRoute,
  AppObjectsIndexRoute: AppObjectsIndexRoute,
  AppPathsIndexRoute: AppPathsIndexRoute,
  AppRoomsIndexRoute: AppRoomsIndexRoute,
  AppScriptsIndexRoute: AppScriptsIndexRoute,
  AppShadersIndexRoute: AppShadersIndexRoute,
  AppSpritesIndexRoute: AppSpritesIndexRoute,
  AppStringsIndexRoute: AppStringsIndexRoute,
  AppTextureGroupsIndexRoute: AppTextureGroupsIndexRoute,
  AppTexturePagesIndexRoute: AppTexturePagesIndexRoute,
  AppTileSetsIndexRoute: AppTileSetsIndexRoute,
  AppTimelinesIndexRoute: AppTimelinesIndexRoute,
  AppVariablesIndexRoute: AppVariablesIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
