<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <ItemGroup>
    <ProjectReference Include="..\lib\UndertaleModTool\UndertaleModLib\UndertaleModLib.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop/wasm-browser-app?view=aspnetcore-10.0#project-configuration -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>

    <PublishDir>$(MSBuildProjectDirectory)/../web/public/dotnet/</PublishDir>

    <!-- Improves performance but higher file size -->
    <!-- <RunAOTCompilation>true</RunAOTCompilation> -->
    <WasmStripILAfterAOT>true</WasmStripILAfterAOT>
    <InvariantGlobalization>true</InvariantGlobalization>
    <InvariantTimezone>true</InvariantTimezone>
  </PropertyGroup>

  <!-- https://github.com/dotnet/runtime/issues/77174#issuecomment-2746107558 -->
  <Target Name="CopyDotnetDTs" AfterTargets="ProcessFrameworkReferences">
    <ItemGroup>
      <_DotnetDTsPath Include="%(RuntimePack.PackageDirectory)\runtimes\browser-wasm\native\dotnet.d.ts" Condition="'%(RuntimePack.Identity)' == 'Microsoft.NETCore.App.Runtime.Mono.browser-wasm'" />

      <Content Include="@(_DotnetDTsPath)">
        <Link>../../../../web/public/dotnet/wwwroot/_framework/dotnet.d.ts</Link>
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
  </Target>
</Project>
