<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <ItemGroup>
    <ProjectReference Include="..\lib\UndertaleModTool\UndertaleModLib\UndertaleModLib.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <!-- https://learn.microsoft.com/en-us/aspnet/core/client-side/dotnet-interop/wasm-browser-app?view=aspnetcore-10.0#project-configuration -->
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
</Project>
