name: Run .NET and Node.js tests

on:
  push:
    branches: ['main']

  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # https://github.com/actions/checkout/releases/tag/v7.0.1
        with:
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # https://github.com/actions/setup-dotnet/releases/tag/v6.0.0
        with:
          dotnet-version: '10.0'
          workloads: wasm-tools

      - name: Compile .NET
        run: dotnet publish -c Release src/

      # - name: Run tests (Debug)
      #   run: dotnet test -c Debug UndertaleModToolWasmTests/

      # - name: Run tests (Release)
      #   run: dotnet test -c Release UndertaleModToolWasmTests/

      # Node.js
      # Do not split to another file, there is a dependency on .NET through `public/dotnet/wwwroot/_framework/dotnet.js`
      - name: Set up Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # https://github.com/actions/setup-node/releases/tag/v7.0.0
        with:
          node-version: lts/*
          cache: 'npm'
          cache-dependency-path: web/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./web

      - name: Build website
        run: npm run build
        working-directory: ./web

      - name: Run ESLint
        run: npm run lint
        working-directory: ./web

      - name: Check JavaScript code style
        run: npm run prettier -- --check
        working-directory: ./web
